### ISSUE TITLE
Tracking issue for migrating to parity-contracts

### ISSUE THREAD

**Issue by sorpaas** [paritytech/contracts#110]
This documents all remaining contracts that requires migration to https://github.com/parity-contracts

- [x] github-hint
- [x] badge-registry
- [x] dapp-registry
- [x] name-registry
- [x] token-registry
- [x] signature-registry

There're codes that are not used in production, so we won't migrate them. This includes:

* Not used: `Bounty.sol`, `Prism.sol`.
* Examples: `CoreVeto.sol`, `DeadMansSwitch.sol`, `DutchAuction.sol`, `DutchBuying.sol`, `FairReceipter.sol`, `OprahBadge.sol`, `Receipter.sol`, `TimedDeposit.sol`, `TokenCalls.sol`.

Below are contracts that are deprecated or removed, and thus will not be moved:

- gavcoin
- sms-verification
- email-verification

**Comment by folsen** [comment]
The latter three (incl sms-verification and email-verification) should not be moved as they are being deprecated and removed.

**Comment by 5chdn** [comment]
regarding token registry, please also migrate the following issues:

- https://github.com/paritytech/contracts/issues/83
- https://github.com/paritytech/parity/issues/6030

**Comment by sorpaas** [comment]
All contracts listed here are migrated. Let's use the corresponding repo for additional issue tracking. Please also let me know if I missed some contracts there.
