### ISSUE TITLE
Execute should always require multi-sig.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/contracts#67]
https://github.com/paritytech/contracts/blob/master/Wallet.sol#L339

ETH is now one of _many_ tokens, including tokens that are just ETH wrappers.  `execute` will allow a single owner to call any contract method without requiring a multi-sig if the daily ETH cap hasn't been reached yet.  This effectively means that for all ETH caps other than `0`, a single owner always has full control of all other assets controlled by the contract.  This may not be obvious to wallet users.

Recommend either making `execute` be `onlymanyowners` or create a separate flag on the wallet (constructor arg) that indicates whether `execute` requires many owners or single owner signature _always_.  Having it based on the daily ETH limit creates a false sense of security that should be avoided.

**Comment by MicahZoltu** [comment]
Actually, reading the code more deeply this may just be a matter of poor documentation.  It appears that if `execute` is calling a function (other than fallback function) it will always require multi-sig.  If my newfound understanding is correct, the comment should be adjusted for clarity.

Also, are there any risks of someone authoring a contract that has a fallback function that does something and then calling that contract via `execute` in order to _actually_ do other operations?  I don't think this is a risk since the context will be the target contract, but I wanted to check and make sure.

**Comment by Ivshti** [comment]
@MicahZoltu if it moves tokens, it has to have `data`. currently, everything with `data` goes into the multi-sig procedure

just a case of good old lack of documentation

**Comment by ngotchac** [comment]
Yes, if data is passed, it should always require multiple signatures from the owners. Please re-open if needed!
