### ISSUE TITLE
DailyLimit do not work properly ?

### ISSUE THREAD

**Issue by branciard** [paritytech/contracts#72]
After the request for review on this multisig in reddit, I start to do some tests.

The m_spentToday increment is done in the underLimit function.
The underLimit is call in this if condition :
`if ((_data.length == 0 && underLimit(_value)) || m_required == 1) {`
 on the execute fonction.
When _data length not equal to 0, m_spentToday is not updated and 
It is possible to spend more than the m_dailyLimit.
see this test here https://github.com/branciard/multisigundertests/blob/master/test/wallet.js#L255

or i miss the point ?

I will continue others tests tomorrow, if this is not too late before the new multisig contract deployment.

**Comment by MicahZoltu** [comment]
I _think_ this is behaving as expected.  In your test, you sign with both owners.  The daily limit is how much ETH someone can send each day _without_ requiring multiple signers of the transaction.

When ETH is sent with multiple signers, then the amount sent should not count towards the daily limit.  Only ETH sent by a single signer (not by multiple signers) should count against the daily limit.  (with the exception of wallets that only have 1 required signer).

**Comment by branciard** [comment]
Thanks MicahZoltu, i make a test on this dailylimit usecase according to your clarification and it works perfectly : https://github.com/branciard/multisigundertests/blob/master/test/wallet.js#L1050
