### ISSUE TITLE
New TokenReg contract

### ISSUE THREAD

**Issue by rstormsf** [paritytech/contracts#83]
https://github.com/rstormsf/tokenReg_parity

Feedback is welcomed.

[With full test coverage](https://rstormsf.github.io/tokenReg_parity/mochawesome-report/mochawesome.html)

Improvements:
1)Reading of `decimals` so people don't have to manually enter it
2)Fix a bug for `tokenCount` (currently it shows wrong number if token has even been `unregistred`
3)Add a method for token owners to update token address by themselves(no more reaching out to @5chdn )
4)remove `indexed string` for events which solidity doesn't support

If approved, I will submit a PR to this repo with gitsubmodule to my repo(because I use truffle)
Then, I will proceed to update Parity Dapp for token registry.

**Comment by 5chdn** [comment]
Thanks.

> 3)Add a method for token owners to update token address by themselves(no more reaching out to @5chdn )

Is it reading the owner of the token contract or how does it determine the correct owner?

> If approved, I will submit a PR to this repo with gitsubmodule to my repo(because I use truffle)

Just for the sake of comparability, could you create a PR against the tokenreg solidity contract here in the repository? 

> Then, I will proceed to update Parity Dapp for token registry.

This would be very much appreciated!

**Comment by 5chdn** [comment]
> 1)Reading of decimals so people don't have to manually enter it

Please be aware, this wont work for all ERC20 tokens, only for those implementing HumanStandardToken.

**Comment by butterstuff** [comment]
will solidity support token names over 3 chars?

**Comment by butterstuff** [comment]
is this the correct thread to ask about the token registry limitations?

**Comment by rstormsf** [comment]
I already solved the problem above: 
https://github.com/rstormsf/tokenReg_parity/tree/check_if_decimals_exists

**Comment by butterstuff** [comment]
it appears that a TLA 3 char limitation still exists in the registration process.

**Comment by 5chdn** [comment]
@rstormsf can you create a PR? I think we can use your repository as submodule.

But we need something to work with and a PR would be the next logical step.

**Comment by cgruber** [comment]
Given that several copies of the "three letter" limitation issues on paritytech/parity have referenced this issue, can we at least confirm that the TLA can be larger than 3 letters?  Several trading ERC-20 tokens are longer than 3 letters, and if a token has a valid contract address, why wouldn't parity allow it to be registered? @butterstuff asked a variant of this question above, but haven't seen any answer or discussion about it.

**Comment by sorpaas** [comment]
Migrated to https://github.com/parity-contracts/token-registry/issues/2
