### ISSUE TITLE
validator contract address datatype return remove first zero in parity public address

### ISSUE THREAD

**Issue by akshay951228** [paritytech/contracts#84]
Input address
![sol](https://user-images.githubusercontent.com/25878082/31584151-5040cae8-b1c6-11e7-878e-b57e8075dd97.png)
ouput address
![re](https://user-images.githubusercontent.com/25878082/31584152-518ee290-b1c6-11e7-8eb9-f4c625117849.png)
How to solve thiss

**Comment by rphmeier** [comment]
This is more of a remix bug. It's just not writing the first zeros, but the address is correct.
